# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3e35c287b042b2065f06299c34077ce80f44c99250f28adaa5b6326e21947c2765a08ec1e5d00d49891caceff66be7a55e241b240ae872a5a5c56e0e9eba1e6d

test:
  secret_key_base: 6c0b60480b78a209b4fd7bb5af2aaad9823c817d9f2c7a4d62af814e1b8c284b2d0c1437e769de44a4a53f8bfab9fbc0f711528b180c572522b1aef7ee80df20

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
